/**
 * Works Cited:
 * This website helped me figure out the basic blackjack rules: https://www.bicyclecards.com/how-to-play/blackjack/
 * Adriana helped me figure out various errors along the way such as importing java.util.ArrayList and errors in my constructor for shoe.
 * I used this to help me with Try/Catches: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
 * I used this to help me figure out NumberFormatExceptions with my numbers in my catch statements: https://airbrake.io/blog/java-exception-handling/numberformatexception
 * I used this to help with insurance (what it is, how much money you get back, etc.): https://www.onlinegambling.com/casino/blackjack/insurance-bet/
 * I used this for scanners: https://www.geeksforgeeks.org/scanner-class-in-java/
 * Daniel helped me with Dealer d1 = new Dealer(); in Game.java
 * This helped with parseInt: https://www.geeksforgeeks.org/string-to-integer-in-java-parseint/
 */